// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2fJupce8xFhFI0wcqlo0qTA_Ckp14WU',
    appId: '1:181464303929:web:281ee7471d66f830c100e8',
    messagingSenderId: '181464303929',
    projectId: 'loginapp-a8ddb',
    authDomain: 'loginapp-a8ddb.firebaseapp.com',
    storageBucket: 'loginapp-a8ddb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpIicEaNn_DxlfRLYRIUS_QJvDJVAIyM',
    appId: '1:181464303929:android:8126983bcee90038c100e8',
    messagingSenderId: '181464303929',
    projectId: 'loginapp-a8ddb',
    storageBucket: 'loginapp-a8ddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuevw3ydaHLe1Wt4ahIJszXyuNLnxI5lg',
    appId: '1:181464303929:ios:cb48db65f588ec02c100e8',
    messagingSenderId: '181464303929',
    projectId: 'loginapp-a8ddb',
    storageBucket: 'loginapp-a8ddb.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuevw3ydaHLe1Wt4ahIJszXyuNLnxI5lg',
    appId: '1:181464303929:ios:cb48db65f588ec02c100e8',
    messagingSenderId: '181464303929',
    projectId: 'loginapp-a8ddb',
    storageBucket: 'loginapp-a8ddb.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv2fJupce8xFhFI0wcqlo0qTA_Ckp14WU',
    appId: '1:181464303929:web:9383ca74fb64835ec100e8',
    messagingSenderId: '181464303929',
    projectId: 'loginapp-a8ddb',
    authDomain: 'loginapp-a8ddb.firebaseapp.com',
    storageBucket: 'loginapp-a8ddb.firebasestorage.app',
  );
}
